/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main2.c                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: bbonaldi <bbonaldi@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/02/14 15:05:51 by bbonaldi          #+#    #+#             */
/*   Updated: 2022/02/14 15:58:19 by bbonaldi         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include <unistd.h>

int main(int argc, char *argv[])
{
	if (2)
	{
		printf("ENTROU NO 1 PRIMEIRO IF\n");
	}
	else
	{			
		printf("ENTROU NO ELSE\n");
	}
}

